/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as NewsRouteImport } from './routes/news'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorsSectorRouteImport } from './routes/sectors.$sector'
import { Route as ProjectsProjectRouteImport } from './routes/projects.$project'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSectorRoute = SectorsSectorRouteImport.update({
  id: '/$sector',
  path: '/$sector',
  getParentRoute: () => SectorsRoute,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sectors': typeof SectorsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/sectors/$sector': typeof SectorsSectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sectors': typeof SectorsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/sectors/$sector': typeof SectorsSectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/news': typeof NewsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sectors': typeof SectorsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/sectors/$sector': typeof SectorsSectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/investors'
    | '/news'
    | '/projects'
    | '/sectors'
    | '/sitemap.xml'
    | '/projects/$project'
    | '/sectors/$sector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/investors'
    | '/news'
    | '/projects'
    | '/sectors'
    | '/sitemap.xml'
    | '/projects/$project'
    | '/sectors/$sector'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/investors'
    | '/news'
    | '/projects'
    | '/sectors'
    | '/sitemap.xml'
    | '/projects/$project'
    | '/sectors/$sector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InvestorsRoute: typeof InvestorsRoute
  NewsRoute: typeof NewsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SectorsRoute: typeof SectorsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$sector': {
      id: '/sectors/$sector'
      path: '/$sector'
      fullPath: '/sectors/$sector'
      preLoaderRoute: typeof SectorsSectorRouteImport
      parentRoute: typeof SectorsRoute
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectRoute: typeof ProjectsProjectRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectRoute: ProjectsProjectRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface SectorsRouteChildren {
  SectorsSectorRoute: typeof SectorsSectorRoute
}

const SectorsRouteChildren: SectorsRouteChildren = {
  SectorsSectorRoute: SectorsSectorRoute,
}

const SectorsRouteWithChildren =
  SectorsRoute._addFileChildren(SectorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InvestorsRoute: InvestorsRoute,
  NewsRoute: NewsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SectorsRoute: SectorsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
